language: php
php:
  - 5.4.3

env:
  - DB=firebird

before_install:
  - sudo service firebird2.5-super start

before_script:
  - pyrus install phpunit/DbUnit
  - phpenv rehash
  - pyrus get
  - ls /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php
  - which phpunit
  - git submodule update --init
  - echo 'CREATE DATABASE "localhost:/tmp/firebird.fdb" PAGE_SIZE = 4096;' > /tmp/create.sql
  - isql-fb -u SYSDBA -p masterkey -i /tmp/create.sql -q

script:
  - phpunit --verbose 

