language: php
php:
  - 5.3
  - 5.4

env:
  - DB=firebird

before_install:
  - sudo service firebird2.5-super start

before_script:
  - pyrus install phpunit/DbUnit
  - phpenv rehash
  - git submodule update --init
  - isql -c "DBF=/tmp/firebird.fdb;UID=SYSDBA;PWD=masterkey;"

script:
  - phpunit --verbose 

