language: php
php:
  - 5.4.3

env:
  - DB=firebird

before_install:
  - sudo service firebird2.5-super start

before_script:
  - git submodule update --init
  - pyrus install phpunit/DbUnit
  - ls -l /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php
  - ls -l /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php/PHPUnit
  - ls -l /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php/PHPUnit/Extensions
  - ls -l /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php/PHPUnit/Extensions/Database
  - cp -r ./DBUnitNoxwizard/PHPUnit/Extensions/Database /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php/PHPUnit/Extensions/Database
  - phpenv rehash
  - ls -l /home/vagrant/.phpenv/versions/5.4.3/share/pyrus/.pear/php/PHPUnit/Extensions/Database
  - echo 'CREATE DATABASE "localhost:/tmp/firebird.fdb" PAGE_SIZE = 4096;' > /tmp/create.sql
  - isql-fb -u SYSDBA -p masterkey -i /tmp/create.sql -q

script:
  - phpunit --verbose 

