language: php
php:
  - 5.3
  - 5.4

env:
  - DB=firebird

before_install:
  - sudo service firebird2.5-super start

before_script:
  - pyrus install phpunit/DbUnit
  - phpenv rehash
  - git submodule update --init

script:
  - phpunit --verbose 

