language: php
php:
  - 5.4.3

env:
  - DB=firebird

before_install:
  - sudo service firebird2.5-super start

before_script:
  - git submodule update --init
  - pyrus install phpunit/DbUnit
  - export PYRUS_PHP_DIR=`pear config-get php_dir`
  - echo $PYRUS_PHP_DIR
  - pyrus get php_dir
  - ls -l ./DBUnitNoxwizard/PHPUnit/Extensions/Database/DB/MetaData/
  - ls -l $PYRUS_PHP_DIR/../share/pyrus/.pear/php/
  - ls -l $PYRUS_PHP_DIR/../share/pyrus/.pear/php//PHPUnit
  - ls -l $PYRUS_PHP_DIR/../share/pyrus/.pear/php//PHPUnit/Extensions
  - ls -l $PYRUS_PHP_DIR/../share/pyrus/.pear/php//PHPUnit/Extensions/Database
  - cp -rf ./DBUnitNoxwizard/PHPUnit/Extensions/Database/* $PYRUS_PHP_DIR/../share/pyrus/.pear/php//PHPUnit/Extensions/Database
  - phpenv rehash
  - ls -l $PYRUS_PHP_DIR/../share/pyrus/.pear/php//PHPUnit/Extensions/Database/DB/
  - ls -l $PYRUS_PHP_DIR/../share/pyrus/.pear/php//PHPUnit/Extensions/Database/DB/MetaData/
  - echo 'CREATE DATABASE "localhost:/tmp/firebird.fdb" PAGE_SIZE = 16384;' > /tmp/create.sql 
  - isql-fb -u SYSDBA -p masterkey -i /tmp/create.sql -q
  - ls -l /tmp/

script:
  - phpunit --verbose 
