language: php
php:
  - 5.3
  - 5.4

env:
  - DB=firebird

before-script:
  - pyrus install phpunit/DbUnit
  - phpenv rehash
  - git submodule update --init

install:
  - sudo service firebird2.5-super start

script:
  - phpunit --verbose 

