language: php
php:
  - 5.3
  - 5.4

env:
  - DB=firebird

before_install:
  - sudo service firebird2.5-super start

before_script:
  - pyrus install phpunit/DbUnit
  - phpenv rehash
  - git submodule update --init
  - isql-fb -u SYSDBA -p masterkey << EOF
CREATE DATABASE "localhost:/tmp/firebird.fdb" PAGE_SIZE = 4096;
EOF

script:
  - phpunit --verbose 

